services:
  - type: web
    name: assesium-backend
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: assesium-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: "7d"
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: FRONTEND_URL
        value: "https://assesium-landing-webpage-v1-0-0-henna.vercel.app"
      - key: DEPLOYED_FRONTEND_URL
        value: "https://assesium.vercel.app"

databases:
  - name: assesium-db
    databaseName: assesium_db
    user: postgres
    plan: free

